server:
  port: ${PORT:9480}

pannybank:
  search:
    queryFilesLocation: classpath*:**/queries/*.yaml
    defaultTemplate: findLoanApplications
    defaultCatalogue: loanapplication

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

elasticsearch:
  port: 9300
  host: 127.0.0.1
  cluster-name: loan_application

spring:
  application:
    name: elastic-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

jms:
  redeliveryPolicy:
    maximumRedeliveries: 1

customer-service:
  ribbon:
    listOfServers: http://localhost:9280
loan-application-service:
  ribbon:
    listOfServers: http://localhost:9380
